FROM golang:1.12-rc-stretch
ENV SRC_DIR=/go/src/github.com/Donders-Institute/hpc-qaas
ADD . $SRC_DIR/
WORKDIR $SRC_DIR
RUN make
EXPOSE 5111
CMD $SRC_DIR/scripts/wait-for-it.sh db:5432 --timeout=0 && echo "Started" && server
